#str
Product_name= input ("Enter the product name:")
Stock = int(input("Enter the stock:"))  
Price = float(input("Enter the price:"))
Ram= eval(input("Enter the available sizes :"))
Reviews=eval(input("Enter the reviews:"))
Payment_mode=eval(input("Enter the payment modes:")) 
Brand=eval(input("Enter the brand details:"))
print(f"Product Name: {Product_name}")
print(f"Stock: {Stock}")
print(f"Price: ${Price}")
print(f"Ram: {Ram}")
print(f"Reviews: {Reviews}")
print(f"Payment_mode options: {Payment_mode}")
print(f"Brand details: {Brand}")
