Movie_Name= input ("Enter the Movie Name:")
AvailableSeats = int(input("Enter the Available Seats:"))  
TicketPrice = float(input("Enter the Ticket price:"))
SeatCategories= eval(input("Enter the Seat Categories :"))
MovieReviews=eval(input("Enter the Movie Reviews:"))
Payment_mode=eval(input("Enter the payment modes:")) 
MovieDetails=eval(input("Enter the Movie Details:"))
print(f"Movie_Name: {Movie_Name}")
print(f"AvailableSeats: {AvailableSeats}")
print(f"TicketPrice: ${TicketPrice}")
print(f"SeatCategories: {SeatCategories}")
print(f"MovieReviews: {MovieReviews}")
print(f"Payment_mode options: {Payment_mode}")
print(f"MovieDetails: {MovieDetails}")

